main: dev.razboy.resonance.Resonance
name: Resonance
version: 1.0.0
api-version: 1.16
commands:
  voiceconnect:
    aliases:
      - vc
    description: "voiceconnectsmthidk"
  webcast:
    description: "broadcastsmthidk"